name: Python Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'  # Replace 'x' with the desired Python version (e.g., '3.6', '3.7', '3.8', '3.9')

    - name: Install requests
      run: |
       python -m pip install requests
    - name: Execute test
      run: python test_file.py  # Replace 'test_file.py' with the name of your test Python file

